### ISSUE TITLE
Basic auth header is lost when render API is called on backend.

### ISSUE THREAD

**Issue by britweb-tim** [nk-crew/lazy-blocks#269]
### Issue description:
On a site hidden with basic http auth, the authorization header is removed when the render api is called.  This 

### Lazy Blocks Version:
3.0.0

### WordPress Version:
6.1

### Any helpful information to reproduce the issue (screenshots, code parts)
Browser: Chrome (Latest) on windows
Server: HestiaCP/Apache2/PHP8.0

Clean wordpress 6.1 install with lazyblocks.  Add basic auth to the .htaccess file

Sign in with basic auth and then log in to wordpress.

Create a new Lazyblock and set the title, move focus away from title

at this point the basic auth dialog pops up again

Each time the render api is called the saved auth is lost again (when the template is edited, etc).

It seems like the Authorization header is stripped off the render api request, which causes it to re-authorize on subsequent requests.

I have a test site you can look at, just let me know where to send the details.

**Comment by Mindgrown** [comment]
I'm having this exact same issue. Any update or interaction with the lazyblocks editor page causes a reauthorization. It makes Lazyblocks completely unusable on a staging server (which is the only place I edit blocks using php)

**Comment by nk-o** [comment]
Hey guys. Checked it locally with Basic Auth and everything is working correctly. Most probably on some hosts, it is working in a different way.

If you can help with it, please, create a private ticket in the "Bug Reports" category here https://www.lazyblocks.com/support/

**Comment by nk-o** [comment]
Looks like this bug is already fixed in this commit https://github.com/nk-crew/lazy-blocks/commit/1cf1083d8ee06a71747e331cc9bbc1805c7cf5b7

I will close the issue for now. If you will see this problem again in the new plugin update, please, let me know.

**Comment by britweb-tim** [comment]
Not fixed I'm afraid, still running into the problem on our staging sites with a login.
